@extends('site/layouts.default')

@section('content')

<div class="container" style="padding-top: 120px;">
    <article>
        <h2 style="text-align: center">TERMOS DE USO DA bank LTDA</h2>

        <p>Última Atualização: 30 de junho de 2020<p>
        <p>Bem vindo(a)! Obrigado por utilizar a bank LTDA!<p>
        <p>Esta aplicação e seu conteúdo ("<b>bank LTDA</b>") são controlados e operados pela própria bank LTDA. <b>Todos os direitos reservados.</b></p>
        <p>Estes termos de uso têm por objeto definir as regras a serem seguidas para a utilização da bank LTDA ("<b>Termos de Uso</b>"), sem prejuízo da aplicação da legislação vigente.</p>
        <p><b>AO UTILIZAR A bank LTDA, VOCÊ AUTOMATICAMENTE CONCORDA COM ESTES TERMOS DE USO, RESPONSABILIZANDO-SE INTEGRALMENTE POR TODOS E QUAISQUER ATOS PRATICADOS POR VOCÊ NA bank LTDA OU EM SERVIÇOS A ELA RELACIONADOS. CASO VOCÊ NÃO CONCORDE COM QUALQUER DOS TERMOS E CONDIÇÕES ABAIXO ESTABELECIDOS, VOCÊ NÃO DEVE UTILIZAR A bank LTDA. VOCÊ TAMBÉM CONCORDA COM OS TERMOS DESCRITOS EM NOSSA POLÍTICA DE PRIVACIDADE. PARA ACESSÁ-LA, <a style="color: #3F4254" href="/politica-de-privacidade"><u> CLIQUE AQUI</u></a></b></p>
        <p>Caso queira nos dar algum feedback sobre a bank LTDA, tenha dúvidas ou precise tratar de qualquer assunto relacionado a estes Termos de Uso, entre em contato conosco através do e-mail <a href="mailto:sac@bank.com.br"style="color: #A5D357">sac@bank.com.br</a> .</p>
        <p>Para a segurança dos usuários, a bank NÃO SOLICITA SENHA, TOKEN, DADOS DE CARTÃO DE CRÉDITO OU OUTROS DADOS BANCÁRIOS DE SEUS CLIENTES POR E-MAIL, TELEFONE OU QUALQUER
        OUTRO CANAL DE ATENDIMENTO PERSONALIZADO. Caso o Usuário seja abordado com solicitações nesse sentido, deverá desconsiderar a solicitação e informar a bank por meio do e-mail de atendimento:
        <a href="mailto:ouvidoria@bank.com.br" style="color: #3F4254">ouvidoria@bank.com.br</a></p>
        <h3>•	O QUE É A bank LTDA?</h3>
        <p>
            <b>Serviços.</b> a bank LTDA é uma plataforma que oferece os seguintes serviços: Somos o aplicativo bank, um novo meio de pagamentos on-line e compras de produtos e serviços disponibilizados para qualquer um que use o aplicativo.<br>
        </p>
        <h3><u>DA CONTA bank</u></h3>
        <p>A Conta bank disponibiliza informações sobre saldo e extrato das movimentações apenas em versão eletrônica, não o fazendo em via impressa. <br>
        O Cliente deverá criar uma Conta bank, na forma indicada no site do bank <a style="color: #3F4254;" href="www.bank.com.br">www.bank.com.br</a> <br>
        Cliente declara estar ciente de que somente poderá ter uma única Conta bank, a qual poderá ser acessada por um ou mais usuários do Cliente previamente cadastrados.<br>
        O Cliente se declara ciente de que a solução de pagamentos do bank se destina tão somente a efetivar pagamentos e recebimentos em Criptoativos e Moeda Corrente Nacional, bem como assegura que todos os recursos creditados na Conta bank são oriundos de fontes lícitas e são declarados às autoridades competentes.<br>
        A bank manterá os recursos constantes na Conta bank do Cliente em conta bancária de titularidade do bank, em instituição financeira de escolha deste último. Independentemente do período em que ficarem depositados, os recursos mantidos na Conta bank não serão atualizados monetariamente, bem como não haverá incidência de juros ou qualquer índice de remuneração, exceto na contratação do serviço denominado bank Mais, que remunera o USUÁRIO em Criptoativos pelos saldos custodiados na plataforma.<br>
        A qualquer momento o Cliente poderá, desde que haja saldo suficiente para arcar com os custos do saque, solicitar na dashboard ou na API da bank a transferência de valores de sua Conta bank para a conta bancária de sua titularidade cadastrada no bank.<br>
        O Cliente poderá ativar na dashboard ou na API do bank a opção de saque automático, o qual será por período definido.<br>
        A solicitação de saque da Conta bank para a conta bancária do Cliente somente será cumprida se a instituição financeira indicada estiver devidamente cadastrada no Sistema Brasileiro de Pagamentos do Banco Central do Brasil.<br>
        <b>A bank pode SUSPENDER IMEDIATAMENTE a disponibilização de todas as funcionalidades da solução de pagamentos e serviços, se suspeitar que as atividades do Cliente ou do(s) outro(s) recebedor(es) são ilícitas, direta ou indiretamente, ou se suspeitar que, em razão de variáveis de risco, o Cliente, nos 6 (seis) meses seguintes, poderá sofrer.<br>
        No prazo de 2 (dois) dias úteis após a suspensão, o bank enviará comunicado ao Cliente, expondo as razões para as suas suspeitas. O Cliente terá o prazo de 15 (quinze) dias, contados do recebimento do comunicado, para respondê-lo, aduzindo suas razões e, se for o caso, propondo soluções para os eventuais problemas.<br>
        Depois da resposta ou de sua ausência, o bank, se satisfeito, comunicará ao Cliente o desbloqueio da solução de pagamentos ou, se não satisfeito com a resposta (ou sua ausência), a denúncia do contrato.</b></p>
        <ul>
            <li><b>Suspensão.</b> Nós nos reservamos o direito de suspender ou cancelar, a qualquer momento, o seu acesso à aplicação em caso de suspeita de fraude, obtenção de benefício ou vantagem de forma ilícita, ou pelo não cumprimento de quaisquer condições previstas nestes Termos de Uso, na Política de Privacidade ou na legislação aplicável. Nesses casos, não será devida qualquer indenização a você, e a bank LTDA poderá promover a competente ação de regresso, se necessário, bem como tomar quaisquer outras medidas necessárias para perseguir e resguardar seus interesses.</li>
        </ul>
        <h3>•	COMO ACESSO A bank LTDA?</h3>
        <ul>
            <li><b>Acesso.</b> Para acessar a bank LTDA e utilizar suas funcionalidades é necessário efetuar um cadastro. Para cadastrar-se, você nos fornecerá informações pessoais, conforme descrito em nossa Política de Privacidade. Para saber mais sobre a privacidade de suas informações pessoais na bank LTDA, acesse nossa Política de Privacidade.</li>
            <li><b>Idade de Utilização.</b> Para utilizar a bank LTDA, você deve ter pelo menos 18 (dezoito) anos. Caso você tenha idade inferior, você poderá utilizar a bank LTDA desde que com a supervisão dos seus pais ou responsáveis legais e desde que eles tenham <b>lido e concordado expressamente</b> com estes Termos de Uso, através da seguinte solução técnica: Cadastro dos responsáveis antecipadamente junto a plataforma, devendo portanto ser indicado e vinculado ao cadastro do menores de 18 anos, Os responsáveis deverão fornecer documentos pessoais, para validarem junto ao Compliance da bank.</li>
            <li><b>Titularidade.</b> A partir do cadastro, você será titular de uma conta que somente poderá ser acessada por você. Caso a bank LTDA detecte alguma conta feita a partir de informações falsas, por usuários que, por exemplo, não possuem a idade mínima permitida, essa conta será automaticamente deletada.</li>
            <li><b>Atualização das Informações.</b> Desde já, você se compromete a manter as suas informações pessoais atualizadas. Você também concorda que irá manter o seu login e senha seguros e fora do alcance de terceiros, e não permitirá que a sua conta na bank LTDA seja usada por outras pessoas. Dessa forma, o usuário responsabiliza-se por todas as ações realizadas em sua conta.</li>
            <li><b>Conexão via Terceiros.</b> Alternativamente, a bank LTDA poderá te oferecer a possibilidade de realizar seu cadastro por meio de sua conta de serviços de terceiros como Facebook, Google, twitter, mas não apenas estes. Nessa hipótese, você autoriza a bank LTDA a acessar, armazenar e utilizar as informações fornecidas por terceiros a fim de criar a sua conta na bank LTDA. a bank LTDA reafirma que NÃO tem qualquer ligação com esses terceiros, não possuindo qualquer responsabilidade, tampouco garantindo, em qualquer hipótese, os produtos ou serviços fornecidos por eles. </li>
        </ul>
        <h3>•	A RELAÇÃO CONTRATUAL ENTRE A bank LTDA E O USUÁRIO</h3>
        <ul>
            <li><b>Relação Contratual.</b> Os serviços e o conteúdo oferecidos pela plataforma são propriedade da bank LTDA. Ao estabelecer o contrato que permite ao usuário o gozo das funcionalidades do sistema, a bank LTDA está oferecendo uma licença de uso, que é não-exclusiva, limitada, revogável e de uso pessoal. É da liberalidade do usuário subscrever a qualquer plano oferecido pela bank LTDA, sujeito às regras descritas nesses Termos de Uso.</li>
            <li><b>Compra de Produtos.</b> Somado ao oferecimento da subscrição aos planos da bank LTDA, nossa plataforma permitirá a compra de produtos nos estabelecimentos com parceria com a bank. A compra desses produtos estará sujeita às regras de licenciamento, dispostas na plataforma e/ou nesses Termos de Uso. Caso tais produtos envolvam a integração com plataformas de terceiros, o usuário também estará sujeito aos Termos de Uso, Política de Privacidade e Especificações de Segurança de tal terceiro. </li>
            <li><b>Utilização do Saldo.</b> Quando contratar nossos serviços, você poderá fazer transações até o Limite de saldo contratado, além de acessar seu extrato pelo aplicativo a qualquer momento, ou mensalmente pelo seu e-mail. Você também poderá visualizar pelo aplicativo a contratação de serviços ou pagamentos realizados, bem colocar mais saldo ou utilizar para transferência entre USUÁRIOS.</li>
        </ul>
        <h3>•	ASSINATURA E CANCELAMENTO DE PLANOS</h3>
        <ul>
            <li>Os Serviços disponibilizados pela Plataforma bank são do tipo CUSTO POR TRANSAÇÃO, configurando, assim, uma relação de serviços não continua, a qual se renova mediante a utilização dos serviços de transações, efetivado mediante a taxa por transação, de modo que o usuário pagará os serviços após a prestação referente ao serviço utilizado, sendo um serviço pago mediante a utilização. O pagamento será feito mediante desconto nas transações a serem disponibilizados na própria Plataforma bank. Os valores poderão sofrer alterações, mediante o prévio aviso aos USUÁRIOS.</li>
            <li><b>Modo de Subscrição.</b> A subscrição ao(s) plano(s) pago(s) requer o pagamento antecipado para a subscrição ao plano. Dessa forma, você estará pagando hoje pelo acesso durante o próximo mês corrente. Caso o dia em que o pagamento é efetuado não se repita todos os meses (por exemplo: 31), o pagamento será cobrado no dia útil anterior ao que eventualmente ocorreria caso essa data existisse no mês em questão (por exemplo: 28 ou 30). Haverá renovação automática do plano, a não ser que você manifeste-se contrariamente requerendo o cancelamento, antes da data de faturamento.</li>
            <li><b>Cancelamento da Subscrição.</b> O cancelamento da subscrição ao plano pode ser realizado a qualquer tempo pelo usuário e será entendido como manifestação expressa de que não pretende renovar a licença no próximo período ainda não contabilizado para fins de cobrança. O cancelamento não enseja qualquer dever aa bank LTDA de realizar a devolução do pagamento do mês no qual o usuário optou por não renovar a relação contratual.</li>
            <li><b>Trânsito entre Planos.</b> Nós da bank LTDA sabemos que cada um dos planos é mais adequado para solucionar determinados problemas do usuário. Pensando nisso, oferecemos a possibilidade de você transitar entre os planos (sujeito às mudanças de disponibilidade de recursos oferecidas por cada um), editando ou fazendo upgrade/downgrade de sua subscrição. É importante ressaltar que o usuário que deseja cancelar ou sair das Versões Pagas não perderá sua conta nem o conteúdo gerado, ele apenas virará um usuário do plano gratuito, perdendo acesso às features oferecidas anteriormente.</li>
            <li><b>In-App Purchases.</b> A aplicação possui funcionalidades que podem ser compradas dentro da plataforma, as chamadas “In-App Purchases”. As eventuais compras desses serviços ocorrerão de maneira semelhante ao disposto acima.</li>
        </ul>
        <h3>•	COMO SÃO FEITOS OS PAGAMENTOS NA bank LTDA?</h3>
        <ul>
            <li><b>Meio de Pagamento.</b> Os pagamentos efetuados na bank LTDA deverão ser realizados dentro da aplicação, por meio de Depósito Bancário de mesma titularidade, Criptoativos e Boletos Bancários de mesma titularidade. </li>
            <li><b>Preço Final.</b> O preço pago por você é final e não reembolsável, a menos que diversamente determinado pela bank LTDA. a bank LTDA reserva-se o direito de estabelecer, remover e/ou revisar o preço relativo a todos os serviços ou bens obtidos por meio do uso da aplicação a qualquer momento. Nunca alteraremos o valor da sua subscrição sem antes avisá-lo.</li>
            <li><b>Recolhimento de Impostos.</b> Se houver a incidência de qualquer imposto, o usuário será responsável por seu recolhimento. Em caso de eventual recolhimento por parte da aplicação, a mesma explicita que repassará ao usuário no preço.</li>
            <li><b>Confirmação.</b> A confirmação do pagamento por meio da aplicação ocorrerá em até 4 (quatro) dias úteis. O processamento das informações de pagamento e a confirmação do pagamento serão realizados por sistemas de terceiros (ex. instituição financeira ou administradora do cartão de crédito), sendo o aplicativo uma mera interface entre o cliente e esses sistemas.</li>
            <li><b>Prazo mínimo.</b> Certos produtos ou promoções da bank LTDA podem exigir um prazo mínimo de assinatura. É importante que o usuário esteja ciente de que, caso decida não utilizar mais tais produtos antes do prazo mínimo de assinatura, podem ser cobradas tarifas adicionais.</li>
            <li><b>Código Promocional.</b> Caso a bank LTDA crie algum código promocional (por exemplo, cupom de desconto), este deve ser usado de forma legal para a finalidade e o público ou usuário específico a que se destina, seguindo todas suas condições. O código promocional pode ser cancelado caso se verifique que foi transferido, vendido ou utilizado com erro, fraude, ilegalidade ou violação às condições do respectivo código.</li>
        </ul>
        <h3>•	QUAIS SÃO OS DIREITOS DA bank LTDA SOBRE A APLICAÇÃO?</h3>
        <ul>
            <li><b>Nossos Direitos.</b> Todos os direitos relativos à bank LTDA e suas funcionalidades são de propriedade exclusiva da bank LTDA, inclusive no que diz respeito aos seus textos, imagens, layouts, software, códigos, bases de dados, gráficos, artigos, fotografias e demais conteúdos produzidos direta ou indiretamente pela bank LTDA (“Conteúdo da bank LTDA”). O Conteúdo da bank LTDA é protegido pela lei de direitos autorais e de propriedade intelectual. É proibido usar, copiar, reproduzir, modificar, traduzir, publicar, transmitir, distribuir, executar, fazer o upload, exibir, licenciar, vender ou explorar e fazer engenharia reversa do Conteúdo da bank LTDA, para qualquer finalidade, sem o consentimento prévio e expresso da bank LTDA. Qualquer uso não autorizado do Conteúdo da bank LTDA será considerado como violação dos direitos autorais e de propriedade intelectual da bank LTDA.</li>
        </ul>
        <h3>•	PROPRIEDADE INTELECTUAL SOBRE O SOFTWARE E OS MATERIAIS DISPONIBILIZADOS</h3>
        <ul>
            <li><b>Propriedade Intelectual.</b> Para nós da bank LTDA, a qualidade dos materiais disponibilizados ao usuário é de suma importância. A criação deles é fruto de muito trabalho e dedicação de nossos desenvolvedores. Por isso, reafirmamos que a bank LTDA garante que todos os direitos, título e interesse (incluindo, mas não apenas, os direitos autorais, marcas e outros de propriedade intelectual) sobre o serviço disponibilizado por nós permanecerão sob a titularidade da bank LTDA.</li>
            <li><b>Não-aquisição de Direitos.</b> O usuário não adquirirá nenhum direito de propriedade sobre os serviços e conteúdo da bank LTDA, exceto quando haja outorga expressa neste Termos de Uso.</li>
            <li><b>Download de Conteúdo. É proibido que o usuário faça o download de nosso conteúdo com o intuito de armazená-lo em banco de dados para oferecer para terceiro que não seja o próprio usuário. Veda-se, também, que o conteúdo disponibilizado por nós seja usado para criar uma base de dados ou um serviço que possa concorrer de qualquer maneira com o nosso negócio.</b></li>
        </ul>
        <h3>•	RECLAMAÇÕES SOBRE VIOLAÇÃO DE DIREITO AUTORAL</h3>
        <ul>
            <li><b>•	Infringência de Direitos.</b> Alegações de infringência de direito autoral de qualquer conteúdo disponível na bank LTDA devem ser encaminhadas por meio do e-mail contato@bank.com.br.</li>
        </ul>
            <h3>•	RESPONSABILIDADES DO USUÁRIO E DA bank LTDA</h3>
        <ul>
            <li><b>Responsabilidade pelo Uso.</b> Você é exclusivamente responsável pelo uso da bank LTDA e deverá respeitar as regras destes Termos de Uso, bem como a legislação aplicável à bank LTDA.</li>
            <li><b>Responsabilização por Eventuais Danos.</b> a bank LTDA, seu controlador, suas afiliadas, parceiras ou funcionários não serão, em hipótese alguma, responsabilizados por danos diretos ou indiretos que resultem de, ou que tenham relação com o acesso, uso ou a incapacidade de acessar ou utilizar a bank LTDA.</li>
            <li><b>Não-Responsabilização. TENDO EM VISTA AS CARACTERÍSTICAS INERENTES AO AMBIENTE DA INTERNET, A bank LTDA NÃO SE RESPONSABILIZA POR INTERRUPÇÕES OU SUSPENSÕES DE CONEXÃO, TRANSMISSÕES DE COMPUTADOR INCOMPLETAS OU QUE FALHEM, BEM COMO POR FALHA TÉCNICA DE QUALQUER TIPO, INCLUINDO, MAS NÃO SE LIMITANDO, AO MAU FUNCIONAMENTO ELETRÔNICO DE QUALQUER REDE, HARDWARE OU SOFTWARE. A INDISPONIBILIDADE DE ACESSO À INTERNET OU À bank LTDA, ASSIM COMO QUALQUER INFORMAÇÃO INCORRETA OU INCOMPLETA SOBRE A bank LTDA E QUALQUER FALHA HUMANA, TÉCNICA OU DE QUALQUER OUTRO TIPO NO PROCESSAMENTO DAS INFORMAÇÕES DA bank LTDA NÃO SERÃO CONSIDERADAS RESPONSABILIDADE DA bank LTDA. A bank LTDA SE EXIME DE QUALQUER RESPONSABILIDADE PROVENIENTE DE TAIS FATOS E/OU ATOS.</b></li>
            <li><b>Perda de Lucros.</b> Quando permitido por lei, a bank LTDA e os fornecedores ou distribuidores não serão responsáveis por perda de lucros, perda de receita, perda de dados, perdas financeiras ou por danos indiretos, especiais, consequenciais, exemplares ou punitivos.</li>
            <li><b>Manutenção.</b> É de sua inteira responsabilidade manter o ambiente de seu dispositivo (computador, celular, tablet, entre outros) seguro, com o uso de ferramentas disponíveis, como antivírus, firewall, entre outras, de modo a contribuir na prevenção de riscos eletrônicos.</li>
            <li><b>Links Externos.</b> É possível que a bank LTDA possa conter links para sites e aplicativos de terceiros, assim como ter tecnologias integradas. Isso não implica, de maneira alguma, que a bank LTDA endossa, verifica, garante ou possui qualquer ligação com os proprietários desses sites ou aplicativos, não sendo responsável pelo seu conteúdo, precisão, políticas, práticas ou opiniões. a bank LTDA recomenda que você leia os termos de uso e políticas de privacidade de cada site de terceiros ou serviço que o usuário vier a visitar ou utilizar.</li>
            <li><b>Exclusão de Responsabilidade.</b> Quando a bank LTDA facilita a interação de você com prestadores terceiros independentes, como patrocinadores, anunciantes e empresas que utilizam a ferramenta bank, isso não significa que a bank LTDA endossa, verifica, garante, possui qualquer ligação ou recomenda esses terceiros. NESSAS SITUAÇÕES, a bank LTDA ATUA COMO MERA FACILITADORA DA TRANSAÇÃO ENTRE VOCÊ E TAIS TERCEIROS, DE MODO QUE a bank LTDA NÃO É FORNECEDORA DE BENS OU SERVIÇOS, OS QUAIS SÃO PRESTADOS DIRETAMENTE POR TERCEIROS PRESTADORES INDEPENDENTES. a bank LTDA NÃO SERÁ, EM HIPÓTESE ALGUMA, RESPONSÁVEL POR TAIS PRODUTOS OU SERVIÇOS DE TERCEIROS FORNECEDORES E REITERAMOS A NECESSIDADE DO USUÁRIO LER, ANALISAR E ACEITAR OS TERMOS DE USO DAS PLATAFORMAS QUE POSSAM TER ALGUMA INFERFACE CONOSCO. </li>
            <li style="color: #888;">A bank não será responsável perante o USUÁRIO e não indenizará o USUÁRIO por perdas, danos e despesas devido a uma razão pela qual a bank não possa ser responsabilizada nos termos da lei aplicável.</li>
        </ul>
        <h3>•	COMO A bank LTDA LIDA COM O CONTEÚDO QUE VOCÊ E OUTROS USUÁRIOS PRODUZEM?</h3>
        <ul>
            <li><b>Criação de Conteúdo.</b> a bank LTDA poderá, a seu exclusivo critério, permitir que você ou qualquer outro usuário apresente, carregue, publique ou disponibilize, na aplicação, conteúdo ou informações de texto, imagem, áudio ou vídeo <b>(“Conteúdo de Usuário”).</b></li>
            <li><b>Conteúdos Proibidos.</b> É proibido qualquer Conteúdo de Usuário de caráter difamatório, calunioso, injurioso, violento, pornográfico, obsceno, ofensivo ou ilícito, conforme apuração da bank LTDA a seu critério exclusivo, inclusive informações de propriedade exclusiva pertencentes a outras pessoas ou empresas (ex. direito de autor, marcas), sem a expressa autorização do titular desses direitos, cuja violação não será de responsabilidade da bank LTDA.</li>
            <li><b>Titularidade do Conteúdo.</b> Qualquer Conteúdo de Usuário fornecido por você permanece de sua propriedade. Contudo, ao fornecê-lo para a bank LTDA, você nos outorga uma licença em nível mundial, por prazo indeterminado, gratuita e transferível, e com direito a sublicenciar, usar, copiar, modificar, criar obras derivadas, distribuir, publicar, exibir esse Conteúdo de Usuário em todos os formatos e canais de distribuição possíveis, sem necessidade de novo aviso a você, e sem necessidade de qualquer pagamento, desde que isso esteja relacionado ao funcionamento da plataforma. <b>Ademais, todos os conteúdos serão criptografados são protegidos por criptografia, o que significa que nós seremos “cegos” com relação a esse Conteúdo.</b></li>
            <li><b>Exclusão do Conteúdo.</b>  A bank LTDA poderá, mas não se obriga a analisar, monitorar e remover Conteúdo de Usuário, a critério exclusivo da bank LTDA, a qualquer momento e por qualquer motivo, sem nenhum aviso a você.</li>
        </ul>
        <h3>•	O QUE MAIS EU PRECISO SABER SOBRE ESTES TERMOS DE USO?</h3>
        <ul>
            <li><b>Alterações.</b> Para melhorar sua experiência, a bank LTDA está sempre sendo atualizada. Por esse motivo, estes Termos de Uso podem ser alterados, a qualquer tempo, a fim de refletir os ajustes realizados. No entanto, sempre que ocorrer qualquer modificação, você será previamente informando pelo endereço de e-mail fornecido por você no momento do cadastro ou por um aviso em destaque na aplicação. Caso você não concorde com os novos Termos de Uso, você poderá rejeitá-los, mas, infelizmente, isso significa que você não poderá mais ter acesso e fazer uso da bank LTDA. Se de qualquer maneira você utilizar a bank LTDA mesmo após a alteração destes Termos de Uso, isso significa que <b>você concorda com todas as modificações.</b></li>
            <li><b>Conflito entre Disposições. Em caso de conflito entre estes termos e os termos modificador, os termos posteriores prevalecerão com relação a esse conflito.</b></li>
            <li><b>Lei e Foro.</b> Estes Termos de Uso são regidos pelas leis da República Federativa do Brasil. Quaisquer dúvidas e situações não previstas nestes Termos de Uso serão primeiramente resolvidas pela bank LTDA e, caso persistam, deverão ser solucionadas pelo Foro da Comarca de Curitiba, Paraná, com exclusão de qualquer outro, por mais privilegiado que seja ou venha a ser.</li>
            <li><b>Dúvidas.</b> Caso você tenha alguma dúvida, comentário ou sugestão, por favor, entre em contato conosco por meio do e-mail termo@bank.com.br .</li>
        </ul>
    </article>
</div>


@endsection
